# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bidprice_cache/bidprice_cache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bidprice_cache/bidprice_cache.proto',
  package='bidprice_cache',
  syntax='proto3',
  serialized_pb=_b('\n#bidprice_cache/bidprice_cache.proto\x12\x0e\x62idprice_cache\"\xb6\x01\n\x11\x42idPriceCacheInfo\x12=\n\x05\x65ntry\x18\x01 \x01(\x0e\x32..bidprice_cache.BidPriceCacheInfo.RequestEntry\x12\x0e\n\x06is_bid\x18\x02 \x01(\x08\x12\x11\n\tbid_price\x18\x03 \x01(\x01\x12\x11\n\texpire_at\x18\x04 \x01(\x03\",\n\x0cRequestEntry\x12\x07\n\x03\x42ID\x10\x00\x12\x08\n\x04LOAD\x10\x01\x12\t\n\x05OTHER\x10\x02\x42:Z8gitlab.mobvista.com/voyager/protocols/gen/bidprice_cacheb\x06proto3')
)



_BIDPRICECACHEINFO_REQUESTENTRY = _descriptor.EnumDescriptor(
  name='RequestEntry',
  full_name='bidprice_cache.BidPriceCacheInfo.RequestEntry',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOAD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=194,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_BIDPRICECACHEINFO_REQUESTENTRY)


_BIDPRICECACHEINFO = _descriptor.Descriptor(
  name='BidPriceCacheInfo',
  full_name='bidprice_cache.BidPriceCacheInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='bidprice_cache.BidPriceCacheInfo.entry', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_bid', full_name='bidprice_cache.BidPriceCacheInfo.is_bid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bid_price', full_name='bidprice_cache.BidPriceCacheInfo.bid_price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire_at', full_name='bidprice_cache.BidPriceCacheInfo.expire_at', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BIDPRICECACHEINFO_REQUESTENTRY,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=238,
)

_BIDPRICECACHEINFO.fields_by_name['entry'].enum_type = _BIDPRICECACHEINFO_REQUESTENTRY
_BIDPRICECACHEINFO_REQUESTENTRY.containing_type = _BIDPRICECACHEINFO
DESCRIPTOR.message_types_by_name['BidPriceCacheInfo'] = _BIDPRICECACHEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BidPriceCacheInfo = _reflection.GeneratedProtocolMessageType('BidPriceCacheInfo', (_message.Message,), dict(
  DESCRIPTOR = _BIDPRICECACHEINFO,
  __module__ = 'bidprice_cache.bidprice_cache_pb2'
  # @@protoc_insertion_point(class_scope:bidprice_cache.BidPriceCacheInfo)
  ))
_sym_db.RegisterMessage(BidPriceCacheInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z8gitlab.mobvista.com/voyager/protocols/gen/bidprice_cache'))
# @@protoc_insertion_point(module_scope)
