# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saas_ranker/copy_package_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='saas_ranker/copy_package_info.proto',
  package='package_info_v1',
  syntax='proto3',
  serialized_pb=_b('\n#saas_ranker/copy_package_info.proto\x12\x0fpackage_info_v1\"\xb7\x04\n\x0bPackageInfo\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x10\n\x08\x61pp_size\x18\x03 \x01(\x05\x12\x16\n\x0e\x63ontent_rating\x18\x04 \x01(\x05\x12\x13\n\x0bnum_ratings\x18\x05 \x01(\x05\x12\x0e\n\x06rating\x18\x06 \x01(\x01\x12\x14\n\x0c\x64\x65veloper_id\x18\x07 \x01(\t\x12\x11\n\tbundle_id\x18\x08 \x01(\t\x12\x15\n\rmarket_status\x18\t \x01(\x05\x12\x1f\n\x17normalized_package_name\x18\n \x01(\t\x12\x1f\n\x17normalized_developer_id\x18\x0b \x01(\t\x12\x19\n\x11\x62usiness_category\x18\x0c \x01(\x05\x12\x1c\n\x14mtg_category_level_1\x18\r \x01(\x05\x12\x1c\n\x14mtg_category_level_2\x18\x0e \x01(\x05\x12\x1c\n\x14mtg_category_level_3\x18\x0f \x01(\x05\x12\x15\n\rcategory_type\x18\x10 \x01(\x05\x12\x17\n\x0fmarket_category\x18\x11 \x03(\t\x12\x1b\n\x13market_sub_category\x18\x12 \x03(\t\x12\x18\n\x10similar_packages\x18\x13 \x03(\t\x12\x1a\n\x12\x64\x65veloper_packages\x18\x14 \x03(\t\x12\x37\n\rpackage_ranks\x18\x15 \x03(\x0b\x32 .package_info_v1.PackageRankInfo\"\xa0\x01\n\x0fPackageRankInfo\x12\x1e\n\x16toplist_first_category\x18\x01 \x01(\t\x12\x1f\n\x17toplist_second_category\x18\x02 \x01(\t\x12\x1c\n\x14toplist_payment_type\x18\x03 \x01(\x05\x12\x14\n\x0ctoplist_rank\x18\x04 \x01(\x05\x12\x18\n\x10rank_last_30days\x18\x05 \x03(\x05\x42i\n*com.mobvista.di.dataCenter.metaSampleParseZ;gitlab.mobvista.com/voyager/protocols/gen/copy_package_infob\x06proto3')
)




_PACKAGEINFO = _descriptor.Descriptor(
  name='PackageInfo',
  full_name='package_info_v1.PackageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_name', full_name='package_info_v1.PackageInfo.package_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_name', full_name='package_info_v1.PackageInfo.app_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_size', full_name='package_info_v1.PackageInfo.app_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_rating', full_name='package_info_v1.PackageInfo.content_rating', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_ratings', full_name='package_info_v1.PackageInfo.num_ratings', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='package_info_v1.PackageInfo.rating', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='developer_id', full_name='package_info_v1.PackageInfo.developer_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bundle_id', full_name='package_info_v1.PackageInfo.bundle_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='market_status', full_name='package_info_v1.PackageInfo.market_status', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_package_name', full_name='package_info_v1.PackageInfo.normalized_package_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_developer_id', full_name='package_info_v1.PackageInfo.normalized_developer_id', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business_category', full_name='package_info_v1.PackageInfo.business_category', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtg_category_level_1', full_name='package_info_v1.PackageInfo.mtg_category_level_1', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtg_category_level_2', full_name='package_info_v1.PackageInfo.mtg_category_level_2', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtg_category_level_3', full_name='package_info_v1.PackageInfo.mtg_category_level_3', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category_type', full_name='package_info_v1.PackageInfo.category_type', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='market_category', full_name='package_info_v1.PackageInfo.market_category', index=16,
      number=17, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='market_sub_category', full_name='package_info_v1.PackageInfo.market_sub_category', index=17,
      number=18, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='similar_packages', full_name='package_info_v1.PackageInfo.similar_packages', index=18,
      number=19, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='developer_packages', full_name='package_info_v1.PackageInfo.developer_packages', index=19,
      number=20, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_ranks', full_name='package_info_v1.PackageInfo.package_ranks', index=20,
      number=21, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=624,
)


_PACKAGERANKINFO = _descriptor.Descriptor(
  name='PackageRankInfo',
  full_name='package_info_v1.PackageRankInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='toplist_first_category', full_name='package_info_v1.PackageRankInfo.toplist_first_category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toplist_second_category', full_name='package_info_v1.PackageRankInfo.toplist_second_category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toplist_payment_type', full_name='package_info_v1.PackageRankInfo.toplist_payment_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toplist_rank', full_name='package_info_v1.PackageRankInfo.toplist_rank', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_last_30days', full_name='package_info_v1.PackageRankInfo.rank_last_30days', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=627,
  serialized_end=787,
)

_PACKAGEINFO.fields_by_name['package_ranks'].message_type = _PACKAGERANKINFO
DESCRIPTOR.message_types_by_name['PackageInfo'] = _PACKAGEINFO
DESCRIPTOR.message_types_by_name['PackageRankInfo'] = _PACKAGERANKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PackageInfo = _reflection.GeneratedProtocolMessageType('PackageInfo', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGEINFO,
  __module__ = 'saas_ranker.copy_package_info_pb2'
  # @@protoc_insertion_point(class_scope:package_info_v1.PackageInfo)
  ))
_sym_db.RegisterMessage(PackageInfo)

PackageRankInfo = _reflection.GeneratedProtocolMessageType('PackageRankInfo', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGERANKINFO,
  __module__ = 'saas_ranker.copy_package_info_pb2'
  # @@protoc_insertion_point(class_scope:package_info_v1.PackageRankInfo)
  ))
_sym_db.RegisterMessage(PackageRankInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.mobvista.di.dataCenter.metaSampleParseZ;gitlab.mobvista.com/voyager/protocols/gen/copy_package_info'))
# @@protoc_insertion_point(module_scope)
