# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algo/feature_generator_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from algo import feature_pb2 as algo_dot_feature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='algo/feature_generator_server.proto',
  package='algo',
  syntax='proto3',
  serialized_pb=_b('\n#algo/feature_generator_server.proto\x12\x04\x61lgo\x1a\x12\x61lgo/feature.proto\"\xb4\x01\n\x18\x46\x65\x61tureGenerationRequest\x12\x0f\n\x07timeout\x18\x01 \x01(\x05\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x1c\n\x06\x63\x61ller\x18\x03 \x01(\x0e\x32\x0c.algo.Caller\x12$\n\x08strategy\x18\x04 \x01(\x0b\x32\x12.algo.StrategyInfo\x12/\n\x0craw_features\x18\n \x01(\x0b\x32\x19.algo.RawFeatureDataUnion\"l\n\x19\x46\x65\x61tureGenerationResponse\x12%\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x10.algo.StatusCode\x12(\n\x08\x66\x65\x61tures\x18\n \x01(\x0b\x32\x16.algo.FeatureDataUnion\"\"\n\x0cStrategyInfo\x12\x12\n\nmodel_name\x18\x01 \x01(\t*J\n\x06\x43\x61ller\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nPRE_BIDDER\x10\x01\x12\x11\n\rRANKER_SERVER\x10\x02\x12\x10\n\x0c\x46INAL_BIDDER\x10\x03*9\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x10\n\x0cSERVER_ERROR\x10\x01\x12\x0c\n\x08NO_TASKS\x10\x02\x32o\n\x18\x46\x65\x61tureGenerationService\x12S\n\x10GenerateFeatures\x12\x1e.algo.FeatureGenerationRequest\x1a\x1f.algo.FeatureGenerationResponseB@Z;gitlab.mobvista.com/voyager/protocols/gen/feature-generator\x80\x01\x01\x62\x06proto3')
  ,
  dependencies=[algo_dot_feature__pb2.DESCRIPTOR,])

_CALLER = _descriptor.EnumDescriptor(
  name='Caller',
  full_name='algo.Caller',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRE_BIDDER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANKER_SERVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINAL_BIDDER', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=394,
  serialized_end=468,
)
_sym_db.RegisterEnumDescriptor(_CALLER)

Caller = enum_type_wrapper.EnumTypeWrapper(_CALLER)
_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='algo.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_TASKS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=470,
  serialized_end=527,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
UNKNOWN = 0
PRE_BIDDER = 1
RANKER_SERVER = 2
FINAL_BIDDER = 3
SUCCESS = 0
SERVER_ERROR = 1
NO_TASKS = 2



_FEATUREGENERATIONREQUEST = _descriptor.Descriptor(
  name='FeatureGenerationRequest',
  full_name='algo.FeatureGenerationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout', full_name='algo.FeatureGenerationRequest.timeout', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='algo.FeatureGenerationRequest.request_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='caller', full_name='algo.FeatureGenerationRequest.caller', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='algo.FeatureGenerationRequest.strategy', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_features', full_name='algo.FeatureGenerationRequest.raw_features', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=246,
)


_FEATUREGENERATIONRESPONSE = _descriptor.Descriptor(
  name='FeatureGenerationResponse',
  full_name='algo.FeatureGenerationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='algo.FeatureGenerationResponse.status_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='algo.FeatureGenerationResponse.features', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=356,
)


_STRATEGYINFO = _descriptor.Descriptor(
  name='StrategyInfo',
  full_name='algo.StrategyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='algo.StrategyInfo.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=392,
)

_FEATUREGENERATIONREQUEST.fields_by_name['caller'].enum_type = _CALLER
_FEATUREGENERATIONREQUEST.fields_by_name['strategy'].message_type = _STRATEGYINFO
_FEATUREGENERATIONREQUEST.fields_by_name['raw_features'].message_type = algo_dot_feature__pb2._RAWFEATUREDATAUNION
_FEATUREGENERATIONRESPONSE.fields_by_name['status_code'].enum_type = _STATUSCODE
_FEATUREGENERATIONRESPONSE.fields_by_name['features'].message_type = algo_dot_feature__pb2._FEATUREDATAUNION
DESCRIPTOR.message_types_by_name['FeatureGenerationRequest'] = _FEATUREGENERATIONREQUEST
DESCRIPTOR.message_types_by_name['FeatureGenerationResponse'] = _FEATUREGENERATIONRESPONSE
DESCRIPTOR.message_types_by_name['StrategyInfo'] = _STRATEGYINFO
DESCRIPTOR.enum_types_by_name['Caller'] = _CALLER
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureGenerationRequest = _reflection.GeneratedProtocolMessageType('FeatureGenerationRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREGENERATIONREQUEST,
  __module__ = 'algo.feature_generator_server_pb2'
  # @@protoc_insertion_point(class_scope:algo.FeatureGenerationRequest)
  ))
_sym_db.RegisterMessage(FeatureGenerationRequest)

FeatureGenerationResponse = _reflection.GeneratedProtocolMessageType('FeatureGenerationResponse', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREGENERATIONRESPONSE,
  __module__ = 'algo.feature_generator_server_pb2'
  # @@protoc_insertion_point(class_scope:algo.FeatureGenerationResponse)
  ))
_sym_db.RegisterMessage(FeatureGenerationResponse)

StrategyInfo = _reflection.GeneratedProtocolMessageType('StrategyInfo', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGYINFO,
  __module__ = 'algo.feature_generator_server_pb2'
  # @@protoc_insertion_point(class_scope:algo.StrategyInfo)
  ))
_sym_db.RegisterMessage(StrategyInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z;gitlab.mobvista.com/voyager/protocols/gen/feature-generator\200\001\001'))

_FEATUREGENERATIONSERVICE = _descriptor.ServiceDescriptor(
  name='FeatureGenerationService',
  full_name='algo.FeatureGenerationService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=529,
  serialized_end=640,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateFeatures',
    full_name='algo.FeatureGenerationService.GenerateFeatures',
    index=0,
    containing_service=None,
    input_type=_FEATUREGENERATIONREQUEST,
    output_type=_FEATUREGENERATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATUREGENERATIONSERVICE)

DESCRIPTOR.services_by_name['FeatureGenerationService'] = _FEATUREGENERATIONSERVICE

# @@protoc_insertion_point(module_scope)
