# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rts/rts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rts/rts.proto',
  package='rts',
  syntax='proto3',
  serialized_pb=_b('\n\rrts/rts.proto\x12\x03rts\"\xad\x01\n\tFrequency\x12\x0e\n\x06\x61\x64Type\x18\x01 \x01(\x03\x12\x14\n\x0c\x62usinessType\x18\x02 \x01(\x03\x12\x17\n\x0fusersActivation\x18\x03 \x01(\x03\x12\x15\n\rtimeStampList\x18\x04 \x03(\x03\x12\x11\n\ttimeStamp\x18\x05 \x01(\x03\x12\x0f\n\x07\x64\x65vType\x18\x06 \x01(\x03\x12\r\n\x05\x64\x65vId\x18\x07 \x01(\t\x12\x17\n\x0fslideWindowTime\x18\x08 \x01(\x03\"7\n\x0eRedisFrequency\x12%\n\rFrequencyInfo\x18\x01 \x03(\x0b\x32\x0e.rts.Frequency\")\n\x06\x42udget\x12\x0c\n\x04\x63ost\x18\x01 \x03(\x01\x12\x11\n\ttimeStamp\x18\x02 \x01(\x03*B\n\x0fUsersActivation\x12\r\n\tdefaultRt\x10\x00\x12\x0e\n\nactivation\x10\x01\x12\x10\n\x0cnoActivation\x10\x02*P\n\x0c\x42usinessType\x12\x08\n\x04none\x10\x00\x12\x0e\n\nimpression\x10\x01\x12\t\n\x05\x63lick\x10\x02\x12\x0e\n\nconversion\x10\x03\x12\x0b\n\x07install\x10\x04\x42/Z-gitlab.mobvista.com/voyager/protocols/gen/rtsb\x06proto3')
)

_USERSACTIVATION = _descriptor.EnumDescriptor(
  name='UsersActivation',
  full_name='rts.UsersActivation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='defaultRt', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='activation', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='noActivation', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=298,
  serialized_end=364,
)
_sym_db.RegisterEnumDescriptor(_USERSACTIVATION)

UsersActivation = enum_type_wrapper.EnumTypeWrapper(_USERSACTIVATION)
_BUSINESSTYPE = _descriptor.EnumDescriptor(
  name='BusinessType',
  full_name='rts.BusinessType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='impression', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='click', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='conversion', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='install', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=366,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_BUSINESSTYPE)

BusinessType = enum_type_wrapper.EnumTypeWrapper(_BUSINESSTYPE)
defaultRt = 0
activation = 1
noActivation = 2
none = 0
impression = 1
click = 2
conversion = 3
install = 4



_FREQUENCY = _descriptor.Descriptor(
  name='Frequency',
  full_name='rts.Frequency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adType', full_name='rts.Frequency.adType', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='businessType', full_name='rts.Frequency.businessType', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usersActivation', full_name='rts.Frequency.usersActivation', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStampList', full_name='rts.Frequency.timeStampList', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='rts.Frequency.timeStamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='devType', full_name='rts.Frequency.devType', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='devId', full_name='rts.Frequency.devId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slideWindowTime', full_name='rts.Frequency.slideWindowTime', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=196,
)


_REDISFREQUENCY = _descriptor.Descriptor(
  name='RedisFrequency',
  full_name='rts.RedisFrequency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FrequencyInfo', full_name='rts.RedisFrequency.FrequencyInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=253,
)


_BUDGET = _descriptor.Descriptor(
  name='Budget',
  full_name='rts.Budget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cost', full_name='rts.Budget.cost', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='rts.Budget.timeStamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=296,
)

_REDISFREQUENCY.fields_by_name['FrequencyInfo'].message_type = _FREQUENCY
DESCRIPTOR.message_types_by_name['Frequency'] = _FREQUENCY
DESCRIPTOR.message_types_by_name['RedisFrequency'] = _REDISFREQUENCY
DESCRIPTOR.message_types_by_name['Budget'] = _BUDGET
DESCRIPTOR.enum_types_by_name['UsersActivation'] = _USERSACTIVATION
DESCRIPTOR.enum_types_by_name['BusinessType'] = _BUSINESSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frequency = _reflection.GeneratedProtocolMessageType('Frequency', (_message.Message,), dict(
  DESCRIPTOR = _FREQUENCY,
  __module__ = 'rts.rts_pb2'
  # @@protoc_insertion_point(class_scope:rts.Frequency)
  ))
_sym_db.RegisterMessage(Frequency)

RedisFrequency = _reflection.GeneratedProtocolMessageType('RedisFrequency', (_message.Message,), dict(
  DESCRIPTOR = _REDISFREQUENCY,
  __module__ = 'rts.rts_pb2'
  # @@protoc_insertion_point(class_scope:rts.RedisFrequency)
  ))
_sym_db.RegisterMessage(RedisFrequency)

Budget = _reflection.GeneratedProtocolMessageType('Budget', (_message.Message,), dict(
  DESCRIPTOR = _BUDGET,
  __module__ = 'rts.rts_pb2'
  # @@protoc_insertion_point(class_scope:rts.Budget)
  ))
_sym_db.RegisterMessage(Budget)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z-gitlab.mobvista.com/voyager/protocols/gen/rts'))
# @@protoc_insertion_point(module_scope)
