# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_model/request_context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from prebidder import prebidder_context_pb2 as prebidder_dot_prebidder__context__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_model/request_context.proto',
  package='request_context',
  syntax='proto3',
  serialized_pb=_b('\n core_model/request_context.proto\x12\x0frequest_context\x1a!prebidder/prebidder_context.proto\"\x93\x01\n\x0eRequestContext\x12\x33\n\rroot_req_info\x18\x01 \x01(\x0b\x32\x1c.request_context.RootReqInfo\x12L\n\x1dtraffic_value_predict_context\x18\x02 \x01(\x0b\x32%.prebidder.TrafficValuePredictContext\"(\n\x0bRootReqInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x42;Z9gitlab.mobvista.com/voyager/protocols/gen/request_contextb\x06proto3')
  ,
  dependencies=[prebidder_dot_prebidder__context__pb2.DESCRIPTOR,])




_REQUESTCONTEXT = _descriptor.Descriptor(
  name='RequestContext',
  full_name='request_context.RequestContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_req_info', full_name='request_context.RequestContext.root_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_value_predict_context', full_name='request_context.RequestContext.traffic_value_predict_context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=236,
)


_ROOTREQINFO = _descriptor.Descriptor(
  name='RootReqInfo',
  full_name='request_context.RootReqInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='request_context.RootReqInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='request_context.RootReqInfo.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=278,
)

_REQUESTCONTEXT.fields_by_name['root_req_info'].message_type = _ROOTREQINFO
_REQUESTCONTEXT.fields_by_name['traffic_value_predict_context'].message_type = prebidder_dot_prebidder__context__pb2._TRAFFICVALUEPREDICTCONTEXT
DESCRIPTOR.message_types_by_name['RequestContext'] = _REQUESTCONTEXT
DESCRIPTOR.message_types_by_name['RootReqInfo'] = _ROOTREQINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestContext = _reflection.GeneratedProtocolMessageType('RequestContext', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTCONTEXT,
  __module__ = 'core_model.request_context_pb2'
  # @@protoc_insertion_point(class_scope:request_context.RequestContext)
  ))
_sym_db.RegisterMessage(RequestContext)

RootReqInfo = _reflection.GeneratedProtocolMessageType('RootReqInfo', (_message.Message,), dict(
  DESCRIPTOR = _ROOTREQINFO,
  __module__ = 'core_model.request_context_pb2'
  # @@protoc_insertion_point(class_scope:request_context.RootReqInfo)
  ))
_sym_db.RegisterMessage(RootReqInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z9gitlab.mobvista.com/voyager/protocols/gen/request_context'))
# @@protoc_insertion_point(module_scope)
