# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontier/frontier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frontier/frontier.proto',
  package='frontier',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x66rontier/frontier.proto\x12\x08\x66rontier\"R\n\x12\x44ispatchDspRequest\x12\x15\n\roriginal_path\x18\x01 \x01(\t\x12\x14\n\x0crequest_body\x18\x02 \x01(\x0c\x12\x0f\n\x07\x64sp_ids\x18\x03 \x03(\x03\"7\n\x13\x44ispatchDspResponse\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x10\n\x08ret_code\x18\x02 \x01(\x05\x32_\n\x0f\x46rontierService\x12L\n\x0b\x44ispatchDsp\x12\x1c.frontier.DispatchDspRequest\x1a\x1d.frontier.DispatchDspResponse\"\x00\x42\x34Z2gitlab.mobvista.com/voyager/protocols/gen/frontierb\x06proto3')
)




_DISPATCHDSPREQUEST = _descriptor.Descriptor(
  name='DispatchDspRequest',
  full_name='frontier.DispatchDspRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_path', full_name='frontier.DispatchDspRequest.original_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_body', full_name='frontier.DispatchDspRequest.request_body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dsp_ids', full_name='frontier.DispatchDspRequest.dsp_ids', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=119,
)


_DISPATCHDSPRESPONSE = _descriptor.Descriptor(
  name='DispatchDspResponse',
  full_name='frontier.DispatchDspResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='frontier.DispatchDspResponse.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='frontier.DispatchDspResponse.ret_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['DispatchDspRequest'] = _DISPATCHDSPREQUEST
DESCRIPTOR.message_types_by_name['DispatchDspResponse'] = _DISPATCHDSPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DispatchDspRequest = _reflection.GeneratedProtocolMessageType('DispatchDspRequest', (_message.Message,), dict(
  DESCRIPTOR = _DISPATCHDSPREQUEST,
  __module__ = 'frontier.frontier_pb2'
  # @@protoc_insertion_point(class_scope:frontier.DispatchDspRequest)
  ))
_sym_db.RegisterMessage(DispatchDspRequest)

DispatchDspResponse = _reflection.GeneratedProtocolMessageType('DispatchDspResponse', (_message.Message,), dict(
  DESCRIPTOR = _DISPATCHDSPRESPONSE,
  __module__ = 'frontier.frontier_pb2'
  # @@protoc_insertion_point(class_scope:frontier.DispatchDspResponse)
  ))
_sym_db.RegisterMessage(DispatchDspResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z2gitlab.mobvista.com/voyager/protocols/gen/frontier'))

_FRONTIERSERVICE = _descriptor.ServiceDescriptor(
  name='FrontierService',
  full_name='frontier.FrontierService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=178,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='DispatchDsp',
    full_name='frontier.FrontierService.DispatchDsp',
    index=0,
    containing_service=None,
    input_type=_DISPATCHDSPREQUEST,
    output_type=_DISPATCHDSPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRONTIERSERVICE)

DESCRIPTOR.services_by_name['FrontierService'] = _FRONTIERSERVICE

# @@protoc_insertion_point(module_scope)
