# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prebidder/prebidder_context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prebidder/prebidder_context.proto',
  package='prebidder',
  syntax='proto2',
  serialized_pb=_b('\n!prebidder/prebidder_context.proto\x12\tprebidder\"\x1c\n\x1aTrafficValuePredictContextB5Z3gitlab.mobvista.com/voyager/protocols/gen/prebidder')
)




_TRAFFICVALUEPREDICTCONTEXT = _descriptor.Descriptor(
  name='TrafficValuePredictContext',
  full_name='prebidder.TrafficValuePredictContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['TrafficValuePredictContext'] = _TRAFFICVALUEPREDICTCONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficValuePredictContext = _reflection.GeneratedProtocolMessageType('TrafficValuePredictContext', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICVALUEPREDICTCONTEXT,
  __module__ = 'prebidder.prebidder_context_pb2'
  # @@protoc_insertion_point(class_scope:prebidder.TrafficValuePredictContext)
  ))
_sym_db.RegisterMessage(TrafficValuePredictContext)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z3gitlab.mobvista.com/voyager/protocols/gen/prebidder'))
# @@protoc_insertion_point(module_scope)
